# Local dev overrides — active when spring.profiles.active=local

spring.datasource.url=jdbc:mysql://localhost:3306/candidatedb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.kafka.bootstrap-servers=localhost:9092

spring.cloud.consul.discovery.enabled=false
spring.cloud.consul.enabled=false
